AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Authoriser Service
  Root stack for Authoriser service

Parameters:
  LambdaPowerToolsLayerKey:
    Type: String
  Stage:
    Type: String

Globals:
  Function:
      MemorySize: 1408
      Tracing: Active
      Layers:
        - !Ref LambdaPowerToolsLayerKey
        - !Ref AuthoriserServiceLayer
      Runtime: python3.12
      Architectures:
      - x86_64
      CodeUri: src/
      Environment:
        Variables:
          Stage: !Sub ${Stage}
          POWERTOOLS_SERVICE_NAME: AUTHORISER
          POWERTOOLS_LOG_LEVEL: WARN

Resources:

  AuthoriserServiceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
        - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'

  LambdaAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt AuthoriserServiceRole.Arn
      Handler: lambda_authoriser.handler


  AuthoriserServiceLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AuthoriserServiceLayer
      Description: Dependencies for the auth service Lambda function
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.12
      LicenseInfo: MIT
    Metadata:
      BuildMethod: python3.12

Outputs:
  LambdaAuthFunction:
    Value: !GetAtt LambdaAuthFunction.Arn