AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Contact Service
  Root stack for contact service

Parameters:
  LambdaPowerToolsLayerKey:
    Type: String
  Stage:
    Type: String
  Table:
    Type: String
  Release: 
    Type: String
  Debug:
    Type: String
  LambdaAuthFunctionArn:
    Type: String
  IdempotencyTable:
    Type: String
  IdempotencyExpiry:
    Type: String
  EventBusName:
    Type: String

Conditions:
  IsNotDev: !Not [!Equals [!Ref Stage, "dev-v5"]]

Globals:
  Function:
      MemorySize: 1408
      Layers:
        - !Ref LambdaPowerToolsLayerKey
        - !Ref ContactServiceLayer
      Runtime: python3.12
      Architectures:
      - x86_64
      Tracing: Active
      Timeout: 900
      Environment:
        Variables:
          Stage: !Sub ${Stage}
          TableName: !Ref Table
          POWERTOOLS_SERVICE_NAME: CONTACT
          RELEASE: !Ref Release
          DEBUG: !Ref Debug
          IdempotencyTableName: !Ref IdempotencyTable
          IdempotencyExpiry: !Ref IdempotencyExpiry
          EventBusName: !Ref EventBusName
          POWERTOOLS_LOG_LEVEL: WARN

Resources:

  ContactServiceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
        - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'

  ContactPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Description: "Function for Customer Post"
      Handler: contact_post.handler
      Role: !GetAtt ContactServiceRole.Arn

  ContactGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Description: "Function for Customer Get"
      Handler: contact_get.handler
      Role: !GetAtt ContactServiceRole.Arn

  ContactReportBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ContactPutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Description: "Function for Customer Put"
      Handler: contact_put.handler
      Role: !GetAtt ContactServiceRole.Arn

  ContactArchiveFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Description: "Archive Contact"
      Handler: contact_archive.handler
      Role: !GetAtt ContactServiceRole.Arn

  ContactServiceLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ContactServiceLayer
      Description: Dependencies for the contact service Lambda function
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.12
      LicenseInfo: MIT
    Metadata:
      BuildMethod: python3.12

  ContactApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'
        - 'arn:aws:iam::aws:policy/CloudWatchFullAccess'
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
        - 'arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service:
                - 'apigateway.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaInvoke'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - '*'

  ContactApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Stage}
      TracingEnabled: true
      EndpointConfiguration: REGIONAL
      DisableExecuteApiEndpoint: false
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: contact-api.yml

Outputs:
  ContactArchiveFunction:
    Value: !GetAtt ContactArchiveFunction.Arn

  ContactPutFunction:
    Value: !GetAtt ContactPutFunction.Arn

  ContactPostFunction:
    Value: !GetAtt ContactPostFunction.Arn

  ContactGetFunction:
    Value: !GetAtt ContactGetFunction.Arn

  LambdaAuthFunctionArn:
    Value: !Ref LambdaAuthFunctionArn
  ContactApiGatewayApiID:
    Value: !Ref ContactApiGatewayApi
