AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for ASC LVS Backend

Parameters:
  Stage:
    Type: String
  LambdaPowerToolsLayerKey:
    Type: String
  LambdaPandasLayerKey:
    Type: String
  Release:
    Type: String

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      DeletionProtectionEnabled: true
    DeletionPolicy: Retain

  # SpIntegrationService:
  SpIntegrationService:
    Type: AWS::Serverless::Application
    Properties:
      Location: Microservices/SP-Integration/template.yml
      Parameters:
        Stage: !Ref Stage
