AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Invoice Service
  Root stack for invoice service

Parameters:
  LambdaPowerToolsLayerKey:
    Type: String
  Stage:
    Type: String
  Table:
    Type: String
  Release:
    Type: String
  Debug:
    Type: String
  LambdaAuthFunctionArn:
    Type: String
  IdempotencyTable:
    Type: String
  IdempotencyExpiry:
    Type: String
  EventBusName:
    Type: String

Globals:
  Function:
      MemorySize: 1408
      Layers:
        - !Ref LambdaPowerToolsLayerKey
        - !Ref InvoiceServiceLayer
      Runtime: python3.12
      Architectures:
      - x86_64
      Tracing: Active
      Timeout: 900
      Environment:
        Variables:
          Stage: !Sub ${Stage}
          TableName: !Ref Table
          POWERTOOLS_SERVICE_NAME: INVOICE
          RELEASE: !Ref Release
          DEBUG: !Ref Debug
          IdempotencyTableName: !Ref IdempotencyTable
          IdempotencyExpiry: !Ref IdempotencyExpiry
          EventBusName: !Ref EventBusName
          POWERTOOLS_LOG_LEVEL: WARN

Resources:

  InvoiceServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: IdempotencyTableAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:Query'
                Resource: !Ref IdempotencyTable
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
        - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'

  InvoicePostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Description: "Function for Invoice Post"
      Handler: invoice_post.handler
      Role: !GetAtt InvoiceServiceRole.Arn

  InvoiceGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Description: "Function for Invoice Get"
      Handler: invoice_get.handler
      Role: !GetAtt InvoiceServiceRole.Arn

  InvoicePutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Description: "Function for Invoice Put"
      Handler: invoice_put.handler
      Role: !GetAtt InvoiceServiceRole.Arn

  InvoiceArchiveFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Description: "Archive Invoice"
      Handler: invoice_archive.handler
      Role: !GetAtt InvoiceServiceRole.Arn

  InvoiceServiceLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: InvoiceServiceLayer
      Description: Dependencies for the invoice service Lambda function
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.12
      LicenseInfo: MIT
    Metadata:
      BuildMethod: python3.12

  InvoiceApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'
        - 'arn:aws:iam::aws:policy/CloudWatchFullAccess'
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
        - 'arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service:
                - 'apigateway.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaInvoke'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - '*'

  InvoiceApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Stage}
      TracingEnabled: true
      EndpointConfiguration: REGIONAL
      DisableExecuteApiEndpoint: false
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: invoice-api.yml

Outputs:
  InvoiceArchiveFunction:
    Value: !GetAtt InvoiceArchiveFunction.Arn

  InvoicePutFunction:
    Value: !GetAtt InvoicePutFunction.Arn

  InvoicePostFunction:
    Value: !GetAtt InvoicePostFunction.Arn

  InvoiceGetFunction:
    Value: !GetAtt InvoiceGetFunction.Arn

  LambdaAuthFunctionArn:
    Value: !Ref LambdaAuthFunctionArn

  InvoiceApiGatewayApiID:
    Value: !Ref InvoiceApiGatewayApi
